### ISSUE TITLE
Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.

### ISSUE THREAD

**Issue by maxcc0** [form-data/form-data#166]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.
    at FormData.CombinedStream._checkDataSize (C:\Apps\workspace\betty.acdb.ui\node_modules\form-data\node_modules\combined-stream\lib\combined_stream.js:165:19)
    at emitOne (events.js:77:13)
    at PassThrough.emit (events.js:169:7)
    at PassThrough.source.emit (C:\Apps\workspace\betty.acdb.ui\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\lib\delayed_stream.js:30:21)
    at readableAddChunk (_stream_readable.js:146:16)
    at PassThrough.Readable.push (_stream_readable.js:110:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:76:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at PassThrough._transform (_stream_passthrough.js:21:3)

**Comment by alexindigo** [comment]
Do you mind to provide code sample? Thank you.

**Comment by maxcc0** [comment]
Will share the required details in some time. Here's the info I can provide right now:

I am using node-multiparty to parse the form req and when the form emits part, I append it to the form-data.


This error  is originating @ combined-stream.
The default maxDataSize in combined stream is 2MB. 



Here is the code snippet of combined stream:
CombinedStream.prototype._checkDataSize = function() {
  this._updateDataSize();
  if (this.dataSize <= this.maxDataSize) {
    return;
  }

  var message =
    'DelayedStream#maxDataSize of ' + this.maxDataSize + ' bytes exceeded.';
  this._emitError(new Error(message));
};

Can you pls use this info and see what might be causing this issue? Maybe there should be an option to override maxDataSize of combined-stream.

Ps. I really need a quick fix. Thanks!

**Comment by maxcc0** [comment]
Here is the code sample:



let form = new multiparty.Form();

var payload = new FormData();
payload.append('auth', conf.documents.auth);

form.on('error', function(err) {
   tLogger.info('Error parsing form: ' + err.stack);
   callback(null);
});

form.on('field', function(name, value) {
    tLogger.info('got field ' + name + ' == ' + value);
     keywords.push(value);
});

// Parts are emitted when parsing the form
form.on('part', function(part) {
   // filename is defined when this is a file
    if (part.filename) {

      //append the part to the payload which will be sent
       payload.append(part.filename, part, { filename:part.filename});//this is were the error comes
       part.resume();
    }
    part.on('error', function(err) {
      tLogger.error('Error is processing stream' + err);
    });
});

form.on('close', function(){
  I make POST request here.....
})

**Comment by dpvenkatesh-fk** [comment]
We are also facing same issue, did anyone found a solution or workaround for this issue?

Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.

**Comment by maxcc0** [comment]
I took a code and made some changes to it. Here's the copy, do a require for this and use it the way you'd use form-data until a permanent fix is pushed:
 
[form-data.zip](https://github.com/form-data/form-data/files/348283/form-data.zip)

**Comment by pskanawat** [comment]
Do we have proper fix for this issue?

**Comment by alexindigo** [comment]
@maxcc0 Thanks for the fix. Do you mind to create a pull request to this repo? So we can see the nature of the change?

Also, based on the error log, it seems like the issue comes from https://github.com/felixge/node-delayed-stream package, which already set to `Infinity` here: https://github.com/felixge/node-combined-stream/blob/master/lib/combined_stream.js#L44

_PS. And beware of downloading random zip files from internet_ :)

**Comment by alexindigo** [comment]
I see, combined-stream has it's own maxDataSize – https://github.com/felixge/node-combined-stream/blob/master/lib/combined_stream.js#L10

So what you can try here:

```
var payload = new FormData();
payload.maxDataSize = Infinity;
payload.append('auth', conf.documents.auth);
```

And we'd look into ways of allowing custom options at creation time, similar to what combined-stream does. What do you think @DylanPiercey?

**Comment by maxcc0** [comment]
@alexindigo good idea for custom options. And I remember I just removed the maxsize condition from one of the files somewhere (it's working good in production for a year now 😃). I can check that tomorrow and share it here.

**Comment by DylanPiercey** [comment]
@alexindigo what are your thoughts on doing something like:

```js
FormData.MAX_FILE_SIZE = Infinity
```

I personally like this because it doesn't do anything in the browser.

**Comment by alexindigo** [comment]
It's a singleton, so it will affect all instances in your node process, which might be beyond desirable. :)

**Comment by alexindigo** [comment]
@maxcc0 It's a luxury when you can modify files in production :)

**Comment by DylanPiercey** [comment]
@alexindigo yeah I suppose. What about just setting it on the instance? Or do you have something else in mind?

**Comment by alexindigo** [comment]
Yep, there are couple ways of doing it on the instance.

Less obvious, supposedly works "out of the box":

```
var payload = new FormData();
payload.maxDataSize = Infinity;
```

"Classical" approach, doesn't work at the moment:

```
var payload = new FormData({
  maxDataSize: Infinity
});
```

**Comment by DylanPiercey** [comment]
Surprisingly

```js
var payload = new FormData({
  maxDataSize: Infinity
});
```

Works in the browser, so I'm not against it. Although it's probably worth checking that no browsers error out with this.

**Comment by alexindigo** [comment]
It works-works? Or just being ignored? :)

**Comment by DylanPiercey** [comment]
Just being ignored, but that's fine IMO. Another alternative though is just setting the maxDataSize to infinity and pushing that part of the api on the user to check manually?

**Comment by alexindigo** [comment]
👍  Like overloading checkDataSize with custom implementation – I like the idea :)

**Comment by DylanPiercey** [comment]
This way we aren't tied to combined-stream either.
