### ISSUE TITLE
Error in delayed stream : TypeError: source.on is not a function

### ISSUE THREAD

**Issue by cvignac** [form-data/form-data#220]
Hello everybody,
I am trying to upload a file from a NodeJS server to an API that requires POST form-data request :http://docs.octoprint.org/en/master/api/fileops.html#upload-file

When trying to add the file to my form with form.append, I get the following error : 
TypeError: source.on is not a function
    at Function.DelayedStream.create (/home/vignac/Bureau/paztech2/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/vignac/Bureau/paztech2/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/home/vignac/Bureau/paztech2/node_modules/form-data/lib/form_data.js:68:3)

This is my code : 

  var value = {
    'path':'./test.gcode',
    'readable':fs.readFileSync('./test.gcode') 
// it does not change anything if either path or readable is commented 
  } ;
  var options = {
    //'contentType':'text/plain',
    'filename':"test.gcode"
  };
form.append("file",value,options);

Does anybody know why I get this error ?
Thanks !

**Comment by DylanPiercey** [comment]
@cvignac why is value a primitive object? This should work fine in you change value to

```js
var value = fs.createReadStream(__dirname + '/test.gcode')
```

Let me know if this solves your issue.

**Comment by GeoffreyPlitt** [comment]
@cvignac Exact same error, here's my code, how do I fix this?

formdata.append('file', {uri: `file://${uri}`, type: 'video/mp4', name: 'upload.mp4'})

**Comment by cvignac** [comment]
I am not sure at it will help you, but here is what worked for me : 
`let options = {
        method: 'POST',
        url: myurl,
        headers: { 'header1': myheader},
        formData: {
          file: {
            value: fs.createReadStream(path),
            options: { fileName: req.fileName}
          } }};
      request(options,callback)`

The tricky part is that I had to put fileName as an option, It took me a long time to find it out.

**Comment by GeoffreyPlitt** [comment]
Thanks, not sure if that's right for React-Native though.

Here's my (non-test) code, using RN's native FormData, where we don't use your polyfill:
```javascript
let formdata = new FormData()
formdata.append('file', {uri: `file://${uri}`, type: 'video/mp4', name: 'upload.mp4'})
```

That's how it works in RN. So when we do our testing, I was thinking that simply assigning your polyfill to global namespace should work the same way. No?

**Comment by goodhyun** [comment]
We have a similar symptom : 
https://github.com/bitinn/node-fetch/issues/192

**Comment by taemon1337** [comment]
io.on('connection', function(socket) {
  ss(socket).on('create', function(stream, data) {
    var req = request.post(url);
    var form = req.form();
    form.append('message', data.message);

    // doesn't work
    form.append('file', stream);

    // doesn't work
    form.append('file', { value: stream, options: { filename: data.filename }});

    // doesn't work
    var sss = ss.createStream();
    form.append('file', { value: sss, options: { filename: data.filename }});
    stream.pipe(sss);
  });
});

Every option I try still results in the 'source.on is not a function' problem.  It DOES work if I test using a local fs.createReadStream('test.txt')

**Comment by ndugger** [comment]
I'm experiencing this issue as well. It was working fine a few months ago, but revisiting my code, I must have pulled in a newer version of this package, and now I get this error without having changed my usage code.

**Comment by DylanPiercey** [comment]
@GeoffreyPlitt afaik this module has never accepted the uri option. If someone can post an isolated repro I can take a look 😄.

**Comment by Ovyerus** [comment]
I'm getting the same issue, but I'm just appending a string.

```js
let form = new FormData();

form.append('api_key', this.key); // this.key is a string
```

**Comment by nicklatkovich** [comment]
I had a similar error when I created formData as follows:
```
formData: {
	key: id,
	image: fs.createReadStream(path.resolve(imagePath))
}
```
I thought the whole thing was in the file. But the problem was that id was not a string, but an object that was the right string only when converting. Fixed just using the toString method.

```
formData: {
	key: id.toString(),
	image: fs.createReadStream(path.resolve(imagePath))
}
```
Be considerate and check the typeof the fields sent.

**Comment by Fydon** [comment]
I was using [Multer](https://www.npmjs.com/package/multer) to send a file through Express. Using File directly or its stream failed, but using File's [buffer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/841c5d5e2c334972517b49c9adc931bc7b6a3d95/types/multer/index.d.ts#L46) worked.

**Comment by aster2709** [comment]
whats the solution for this guys?

**Comment by Fydon** [comment]
The following worked for me
```
const servicePostData = multer();

this.app // app is express.Application
  .route('/uploadFile')
  .post(servicePostData .single('file'), async (request: express.Request, response: express.Response) => {
    const form = new FormData();
    form.append('file', request.file.buffer, {
      contentType: request.file.mimetype,
      filename: request.file.originalname,
    });
    await fetch(url, {
        body: form,
```

**Comment by GordiNoki** [comment]
I see this is old issue, but if someone finds it, my solution was to provide string data to form.append:
`form.append("credentials", { "username": uname, "password": pass });`
to:
`form.append("credentials", \`{ "username": "${uname}", "password": "${pass}" }\`);`

**Comment by WaifuForever** [comment]
why form data doesn't support nested objects?
