### ISSUE TITLE
HTTPS is not supported

### ISSUE THREAD

**Issue by kmccmk9** [form-data/form-data#347]
Hello,

I'm trying to use this module to send form data over HTTPS. Below you can see my code, which is similar to the test code and the error I'm receiving back.

# **Code:**

   ```js
var form = new FormData();
    form.append('file1', req.frontBuffer);
    form.append('file2', req.backBuffer);

    form.submit({
        headers: {'Authorization': 'LicenseKey xxxxxxx'},
        protocol: 'https',
        host: 'hostnamehere.com',
        method: 'post',
        path: '/Process/False',
        port: 443
        }, function(err, res) {
        if (err)
        {
            console.error('Error:' + err);
        }
        console.log(res.statusCode);
        res.on('data', function(chunk) {
            console.log('body:' + chunk);
        });
        console.log('\r\n\r\n');
        console.log(form);
    });
```

# **Error:**

```js
Error: Protocol "https" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:55:11)
    at Object.exports.request (http.js:31:10)
    at FormData.submit (C:\Users\kylec\Documents\GitHub\project\node_modules\form-data\lib\form_data.js:411:20)
```

**Comment by kmccmk9** [comment]
SOLUTION:

For anyone else struggling, the protocol is **https:** not https

**Comment by alexindigo** [comment]
Yeah, this is node thing, `http.request` expects it like that - https://nodejs.org/docs/latest-v4.x/api/http.html#http_http_request_options_callback
and `url.parse` returns it that way – https://nodejs.org/docs/latest-v4.x/api/url.html#url_url_parsing
