### ISSUE TITLE
Compressing pipes not handled

### ISSUE THREAD

**Issue by jhihn** [form-data/form-data#360]
When returning a file from a compressing pipe:
 ```
  value: fs.createReadStream(process.argv[2]).pipe(zlib.Gzip())
```
The error occurs:
```
Error: Unexpected end of multipart data
    at /Users/..../node_modules/dicer/lib/Dicer.js:62:28
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
Additionally there seems to be no way to indicate the content-encoding is gzip?

**Comment by DylanPiercey** [comment]
@jhihn does it work if you directly compress the entire form?

IE:

```js
form
  .pipe(lib.Gzip())
  .pipe(request)
```

May not work for your use case though.

**Comment by jhihn** [comment]
Sort-of. It does do what it is told, but I have to manually add in the content-encoding header, and the backend only sees the gzip data. I'll follow up with body-parser and see if I can get them to support it.

**Comment by zag2art** [comment]
@jhihn have you managed to get it working?

**Comment by jhihn** [comment]
No, this seems to be a fundamental assumption of node, that the root request won't be compressed, so it's no possible to send it this way.
