### ISSUE TITLE
Test fails because of SSL certs

### ISSUE THREAD

**Issue by yordis** [form-data/form-data#405]
I keep getting this issue

```
yarn test
yarn run v1.9.4
$ rimraf coverage test/tmp
$ istanbul cover test/run.js
[0:00:07 0/19/24 79.2% test-submit-https.js]
_tls_common.js:123
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:123:17)
    at Server (_tls_wrap.js:867:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:84:10)
    at Object.<anonymous> (/Users/ubi/Developer/open-source/form-data/test/integration/test-submit-https.js:41:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/ubi/Developer/open-source/form-data/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
node /Users/ubi/Developer/open-source/form-data/test/integration/test-submit-https.js

1 errors in 24 files (0:00:09)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that the SLL certs needs to be update it.

**Comment by JBtje** [comment]
Certificates are updated in #419
