### ISSUE TITLE
Allow Setting Empty File Name

### ISSUE THREAD

**Issue by codenirvana** [form-data/form-data#412]
I am using [request](https://github.com/request/request) for multipart form upload.
If file source(ReadStream) is not set, I want to still send the file-part with `filename=""`. like:

```
------WebKitFormBoundaryK5aZPhhwAGCZ9xn4
Content-Disposition: form-data; name="datafile"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryK5aZPhhwAGCZ9xn4--
```

But due to [truthy check](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L226) on `filename` its not possible.

Is there any way to send empty `filename`?

**Comment by codenirvana** [comment]
@alexindigo Thanks for the reply.
`options.header` won't overwrite the `Content-Disposition` header value.
Since, [populate](https://github.com/form-data/form-data/blob/master/lib/populate.js#L6) will always pick the destination value, not the source(custom).

**Comment by alexindigo** [comment]
True. Sorry for the confusion.
Unfortunately I don't see an easy way to change the behavior without introducing breaking changes.

For your specific use case though, I'd recommend to augment `FormData.prototype. _getContentDisposition` method.

Something like:

```
var formData = new FormData();

formData._getContentDisposition =() => 'filename=""';

// rest of the code
```

**Comment by codenirvana** [comment]
@alexindigo Yes, that's one way.
Would be great if you consider adding support of this.

**Comment by alexindigo** [comment]
Trying to think of a way to do it without creating breaking change. So if you have ideas – please tell :)

**Comment by lautarodragan** [comment]
I faced the same issue recently. My biggest pain was the error message - it was confusing me a lot. I wound up reading the source code of the library and arrived at these same lines, which allowed me to figure out the name thing. 

In my case I was appending the `req` object provided by Koa (which is an [IncomingMessage
](https://nodejs.org/api/http.html#http_class_http_incomingmessage) and implements the [ReadableStream](https://nodejs.org/api/stream.html#stream_class_stream_readable) interface).

```js
export const PostFile = async (ctx, next) => {
  const formData = new FormData()
  formData.append('content', ctx.request.req }) // this fails
  // formData.append('content', ctx.request.req, { filepath: 'content' }) // this works

  const response = await fetch(`${url}/files`, {
    method: 'post',
    body: formData,
  })

  const json = await response.json()

  ctx.status = 200
  ctx.body = json
} 
```

This throws the following error:

```
[1559059152751] ERROR (7714 on pop-os): The "path" argument must be of type string. Received type undefined
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
        at validateString (internal/validators.js:125:11)
        at Object.basename (path.js:1289:5)
        at FormData._getContentDisposition (/.../node_modules/form-data/lib/form_data.js:233:21)
        at FormData._multiPartHeader (/.../node_modules/form-data/lib/form_data.js:177:33)
        at FormData.append (/.../node_modules/form-data/lib/form_data.js:70:21)
        ...
```

Maybe as a quick improvements we could add a check there and throw a more informative error, or default to empty string.

There seems to be a PR addressing this already: https://github.com/form-data/form-data/pull/421

**Comment by mapleeit** [comment]
FYI, @lautarodragan #421 has been merged. Please wait for next release.
