### ISSUE TITLE
can form-data append a fetch Promise which will resolve to a stream?

### ISSUE THREAD

**Issue by t829702** [form-data/form-data#457]
I see form-data append has already supported multiple streams, including http, request, axios, so

```js
     var f = new FormData();
    f.append("name", request("http://some-site/path/to/file.jpeg"));
```

this works, while for some reason, my client code has already depended on node-fetch, when I change to this fetch API, this does not work

```js
    const fetch = require("node-fetch");

     var f = new FormData();
    f.append("name", fetch("http://some-site/path/to/file.jpeg"));
```

this fetch API returns a Promises which will resolve to a Response, I can chain it to resolve to a stream, but still does not work

```js
    f.append("name", fetch("http://some-site/path/to/file.jpeg")  .then(res => res.body));
```

got console errors

```console
'ERROR:' TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/.../tmp/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/.../tmp/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/Users/.../tmp/node_modules/form-data/lib/form_data.js:74:3)
```

**Comment by nicolasolmos** [comment]
Assuming that you use [this library](https://github.com/request/request#promises--asyncawait) as the request function of your example:

Request its based on the Stream Node.js API.
FormData accepts Node.js Stream objects. That's why it works well with the Request package.

Fetch API retrieves Promises.
I am not sure but I think that FormData does not support Promises.

Chaining .then() method always retrieves a new Promise object. That's why it doesn't work.
It doesn't convert the Promise to a Stream object.
