### ISSUE TITLE
Cannot append ArrayBuffer

### ISSUE THREAD

**Issue by tylerlong** [form-data/form-data#468]
```js
const fs = require('fs');
const FormData = require('form-data');
const formData = new FormData();
const arrayBuffer = new Uint8Array(fs.readFileSync('/Users/.../test.png')).buffer;
formData.append('files[]', arrayBuffer, {
    filename: 'test.png',
    contentType: 'image/png',
});
```

Error:

```
Uncaught TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/.../node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/.../node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/Users/.../node_modules/form-data/lib/form_data.js:74:3)
```

**Comment by C-Saunders** [comment]
My understanding might not be quite right, but arrays aren't a streaming source and aren't supported by form-data. It wouldn't be surprising to me if Uint8Arrays were essentially a special case of array for this purpose.

However, from [this part of the Node docs](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options)
> If the encoding option is specified then this function returns a string. Otherwise it returns a buffer.

Since `fs.readFileSync` returns a buffer, could you do it this way instead?
```js
const fs = require('fs');
const FormData = require('form-data');
const formData = new FormData();
formData.append('files[]', fs.readFileSync('/Users/.../test.png'), {
    filename: 'test.png',
    contentType: 'image/png',
});
```

**Comment by tylerlong** [comment]
@C-Saunders  Thanks.

I was trying to share code between Node.js and browser. 
Later I realized that this library is quite different from the `FormData` in browser.  It doesn't support Blob or File type of data.

I will leave this ticket open. But feel free to close it if there is no plan to change the current behavior.

**Comment by yanquer** [comment]
2024,   ArrayBuffer is not supported yet? 

@tylerlong  how do you share browser-form-data to nodejs ?

**Comment by tylerlong** [comment]
To update every one, I wrote my own FormData implementation and it works for both node and browser: https://github.com/ringcentral/ringcentral-extensible/blob/master/packages/core/src/FormData.ts

My requirement is special that I only need to attach files to the FormData, so my implementation is not a general one.
Here is how I use it: https://github.com/ringcentral/ringcentral-extensible/blob/master/packages/core/src/Utils.ts#L42-L82

**Comment by ljharb** [comment]
@tylerlong if you'd be willing to make a PR here, it'd be appreciated.

**Comment by tylerlong** [comment]
> @tylerlong if you'd be willing to make a PR here, it'd be appreciated.

My implementation is not a general one, it only supports files.

**Comment by oziks** [comment]
If it helps,

I encountered the same problem when using **FormData**. My frontend was passing me a **Uint8Array** which I passed directly into the FormData via:
```js
const formData = new FormData();
formData.append('File', bufferUint8Array);
```
I got the following error: `Uncaught TypeError: source.on is not a function`.

To solve the problem, I simply converted the **Uint8Array** into a **Buffer** using the `Buffer.from(buffer)` method.
