### ISSUE TITLE
FormData doesn't work properly

### ISSUE THREAD

**Issue by darklight9811** [form-data/form-data#503]
## Describe the bug
I actually spent a lot of time debugging if this was a problem with axios, form-data, node or my framework. I narrowed it down to form-data. It actually works properly using the default FormData provided by the browser. But the thing is I need it running with node. I tried parsing it with formidable, nestjs parser and adonisjs v5 parser. All of them work properly using native formdata.

## How to reproduce
Just send any FormData with axios, fetch to an endpoint that will print what you receive. It will print out something like this:

``` json
{
  "----------------------------007181389194487799053447\r\nContent-Disposition: form-data; name": "\"f\"\r\n\r\nt\r\n----------------------------007181389194487799053447--\r\n"
}
```

Since fetch is not native to node.js, I'm using axios for my test script:

``` javascript
import FormData from "form-data";
import axios from "axios";

const f = new FormData();
f.append("f", "t");
axios.post("http://0.0.0.0:3333/", f).then((data) => console.log(data.data)).catch((e) => console.warn(e));
```

**Comment by Yuval-Peled** [comment]
This also doesn't work for me. I tried downgrading  from 4.0.0 to 3.0.1 and to 3.0.0 (which is 2 years old) and it did not help.
I'm suspecting this is something that changed in node.js itself. My version is 14.16.1, the most recent one

**Comment by Thymas1** [comment]
Is there any news here? I belive i have the same issue. form-data implementation that worked a few days ago, now suddenly does not work, logging the form after appending to it, shows it looking the same way as described by @darklight9811

**Comment by Yuval-Peled** [comment]
@Thymas1 I ended up working with native node.js libraries and it's just as easy:
```typescript
const data = new URLSearchParams();
data.append(key, value);
const response = await axios.post(url, data, {headers: {'Content-Type': 'application/x-www-form-urlencoded'}})
```

**Comment by Thymas1** [comment]
Thanks for the response!
Ill try to refactor our code away from form-data to check if that will do the trick.

**Comment by sealover06** [comment]
Hello team, looks like I'm getting a kind of same issue. I'm using:
node -v14.17.3
fetch 
form-data: 4.0.0

`
async function f_signableDocumentUploadOne(p_fileName, p_signatureFormat) {

	let
		finalUrl = _transactionUrl.upload.url.replace('<transactionID>', _transactionID),
		fd = new FormData(),
		rc = 0;

	fd.append('file', fs.createReadStream(p_fileName), { filename : 'contratdemo.pdf' });
	fd.append('id', _transactionID); // transactionID
	fd.append('url', ''); // 1000 char max
	fd.append('name', ''); // 200 char max
	fd.append('hash', ''); // 64 char max
	fd.append('alias', ''); // 200 char max
	fd.append('rank', 0); // integer
	fd.append('keywords', ''); // 1000 char max 
	fd.append('withoutProcessing', false); // boolean
	fd.append('archive', false); // boolean
	fd.append('signatureFormat', p_signatureFormat); // PADES / XADES / CADES
	fd.append('fields', ''); // metadata XML

	let fetchOptions = {
			method: _transactionUrl.upload.method,  // POST in this case
			headers: Object.assign(form.getHeaders()),
			body: fd,
	}; console.dir(fetchOptions);
	
	log(_dashLine, `fetching now: [${finalUrl}]`);
	let
		rsp			= await fetch(finalUrl, fetchOptions);
		rspText = await rsp.text(); log(rspText);
`

fetch returns
`_http_outgoing.js:722
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (false)
    at write_ (_http_outgoing.js:722:11)
    at ClientRequest.write (_http_outgoing.js:687:15)
    at FormData.ondata (internal/streams/legacy.js:20:31)
    at FormData.emit (events.js:375:28)
    at FormData.CombinedStream.write (C:\Users\ddumas\Documents\node\node_modules\combined-stream\lib\combined_stream.js:138:8)
    at FormData.CombinedStream._pipeNext (C:\Users\ddumas\Documents\node\node_modules\combined-stream\lib\combined_stream.js:126:8)
    at FormData.CombinedStream._realGetNext (C:\Users\ddumas\Documents\node\node_modules\combined-stream\lib\combined_stream.js:99:10)
    at FormData.CombinedStream._getNext (C:\Users\ddumas\Documents\node\node_modules\combined-stream\lib\combined_stream.js:82:12)
    at DelayedStream.emit (events.js:387:35)
    at DelayedStream._handleEmit (C:\Users\ddumas\Documents\node\node_modules\delayed-stream\lib\delayed_stream.js:82:15) {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

If I JSON.stringify fd, then the file is not uploaded.

Let me know please what I'm doing wrong.  thanks a lot in advance, Cheers,

**Comment by lsirivong** [comment]
Related to #508?

I've had some issues with file upload content that seem to be resolved by providing `knownLength` as described in that issue.

**Comment by enbermudez** [comment]
Is there any update? I'm having troubles with Node v14.

**Comment by privateOmega** [comment]
Try adding `"Content-Length": formdata.getLengthSync()` in headers, that solved it for me.

**Comment by sealover06** [comment]
Thanks  !

 

___________________________________________________________________

Denys Dumas

 

Tel : +33 6 22 445 445

**Comment by ochov1** [comment]
I am trying to add Buffer from sharp image resizer. 
Is not working

**Comment by CalvinJamesHeath** [comment]
Same issue here.

**Comment by gbubemi22** [comment]
same issue

**Comment by victors1681** [comment]
worked fine on node 16 but does not work on node v18

**Comment by DattaramNaik** [comment]
If you are getting Failed to load data resouces issue 

check your cors setting and request timeOut time

**Comment by zadiaz** [comment]
same issue

**Comment by jlon9-dev** [comment]
> @Thymas1 I ended up working with native node.js libraries and it's just as easy:
> 
> ```ts
> const data = new URLSearchParams();
> data.append(key, value);
> const response = await axios.post(url, data, {headers: {'Content-Type': 'application/x-www-form-urlencoded'}})
> ```
> 
> I'm not sure if this covers all of the use cases that form-data solves, but for me this was enough (and removed a dependency, to boot).

It's works for me! tnks

**Comment by SureEnough** [comment]
> Try adding in headers, that solved it for me.`"Content-Length": formdata.getLengthSync()`

This method is useful, thank you

**Comment by TRYOKETHEPEN** [comment]
For those need formdata on nodejs, please notice:
https://www.npmjs.com/package/formdata-node#comparison
